### PR TITLE
Bump version to 0.1.10 everywhere

### PR DESCRIPTION
**Pull request by captn3m0**
The latest release is `0.1.10`, but the documentation and examples in some places still refer to `0.1.8`

### CODE REVIEW

**Comment by yiranwang52** [comment]
@captn3m0 can you hold on to this diff for a couple of days? 0.1.10 has some problem with some registry implementations; we will release a new version next week.

**Comment by captn3m0** [comment]
>0.1.10 has some problem with some registry implementations
I was facing these during my tests as well. Will wait for the release

**Comment by yiranwang52** [comment]
0.1.11 released.

**Comment by captn3m0** [comment]
@yiranwang52 Changed to `0.1.11` everywhere

**Pull request merged**
