### PR TITLE
only save one of repeat layers when Pull and Push, main about 0 layer

### PR DESCRIPTION
**Pull request by wutongjie23hao**
when I test function Pull, there is something wrong.
failed to perform "verifyStateHelper"
the reason is that there may be two or more 0 layer in a images's layers

### CODE REVIEW

**Comment by evelynl94** [comment]
> the reason is that there may be two or more 0 layer in a images's layers

@wutongjie23hao Did you mean `GetLayerDigests` returns duplicated layers? Could you paste the exact error/log you got as well as your Dockerfile to reproduce it?

**Comment by wutongjie23hao** [comment]
@evelynl94 I only test function Pull. I try to pull a image that contains duplicated 0 layers, the error occured.

**Comment by josecv** [comment]
Hi,

We are also seeing this behaviour. It seems some images are built with duplicated layers; apparently the docker daemon can tolerate this but makisu cannot.

Here is a simple repro dockerfile:

```Dockerfile
FROM namely/gen-grpc-gateway:1.19_1 as compile
```

It seems like this particular image (`namely/gen-grpc-gateway:1.19_1`) has a manifest that looks like this:


```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 5964,
      "digest": "sha256:2f1c2162ac4659823edb4dba67e112ffc4d1e7f567bf32b182f4e0d49e663644"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2207025,
         "digest": "sha256:cd784148e3483c2c86c50a48e535302ab0288bebd587accf40b714fffd0646b3"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1938414,
         "digest": "sha256:4487cffa87c4c60c992514b954119938ecefc30e6e380fb697cfd0276e8daccd"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 59317373,
         "digest": "sha256:54fad2427c6186a2b85ce300756c9b50ed79037de5c0fd208308af048a795027"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 16181293,
         "digest": "sha256:bdfefb52c6970b3a5925b20b671ef45a6d96e6751d75c9d8ada914208626506a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 79498809,
         "digest": "sha256:6462662662d6726f29572cc80048799a50766a923434634ae2379db320c8825a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 775077,
         "digest": "sha256:8d21b3766466e8ec2c9cfacba03b2999bc2141c9ae2c30cd02c50ef1fca350e5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1550570,
         "digest": "sha256:4ec2e2984fcaa860ef79a390841706b4c752f163d12c0f7003786b0908d7dabb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 380891,
         "digest": "sha256:66b386519d0d220d86d2abd53b8749cfa4ab7c6eaa803141b35321f101d98d1c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 5283377,
         "digest": "sha256:5737a7e799e85c7495ccdbdb45371c8d5d4928a41abc2fa24107ec5419833a81"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 22875191,
         "digest": "sha256:a5c6aa27509553d61d99372c2ee35827cf3a5968a6b9f7b2c8cc907eae367df7"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 5528565,
         "digest": "sha256:9d56b356f100ed22f4970c7f85d9ae217f270bfa4bf3cb2e8f2822884eb463ee"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 15517,
         "digest": "sha256:333f632d61d70b4adb54211d3546033a06ce4b53ecab3c28145b611b900bebbf"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2387,
         "digest": "sha256:398065a09fce3cbc1644a4b1cc511b6dbf2d944b7f40cbc59553c6d6a7d9e196"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2387,
         "digest": "sha256:398065a09fce3cbc1644a4b1cc511b6dbf2d944b7f40cbc59553c6d6a7d9e196"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 93,
         "digest": "sha256:e6aee83fd6fb19411066b966545cf1a06b86eb93ac59820ca0c796d11ad6f691"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 4817,
         "digest": "sha256:ddccd44993fc5e316af01321d90e12dc9bb8de5e2a1e7b93d696e116b30df388"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1066,
         "digest": "sha256:ae3e95f70ef458323f7d6ebf57c5a5624b308188b3b189b52c6fd9d2bbe8c7c1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1063,
         "digest": "sha256:e4b2b3e6c854c9816947ce4abb93da34733d1c14cfa8b630af2173977bab5a56"
      }
   ]
}
```

Notice how layer `398065a09fce3cbc1644a4b1cc511b6dbf2d944b7f40cbc59553c6d6a7d9e196` appears in the manifest twice.

**Comment by yiranwang52** [comment]
I think this change needs more tests; I will add them after merging this.

**Pull request merged**
