### PR TITLE
Fix registry config parsing

### LINKED ISSUE #167: basic authentication with json registry config doesn't work
In our company we use artifactory with anonymous downloads allowed. To be able to fetch a base image I use following `makisu.yaml` and it works just fine
```
artifactory.mycompany.com:
  docker-registry:
    security:
      tls:
        client:
          disabled: true
      basic:
        username: ""
        password: ""
```

But being converted to json it just won't work
```
{ "artifactory.mycompany.com": { "docker-registry": { "security": { "tls": { "client": { "disabled": true } }, "basic": { "username": "", "password": "" } } } } }
```
I tried using `{}`s for empty values, tried removing `basic` block, etc.. It never works.

Seems, that json mapping is broken.

Let me know, if any other details are needed to reproduce this.

May be related to #157

### PR DESCRIPTION
**Pull request by evelynl94**
fixes #167

### CODE REVIEW

**Comment by IoanaStanescu** [comment]
In which version of the docker image is this fix? I tried with latest (v1.0.9) and it only accepts a file for the registry config

**Comment by evelynl94** [comment]
> In which version of the docker image is this fix? I tried with latest (v0.1.9) and it only accepts a file for the registry config

Latest release should contain this. 
Also here is how command is parsed https://github.com/uber/makisu/blob/master/bin/makisu/cmd/utils.go#L50

**Comment by yiranwang52** [comment]
@loanaStanescu what command did you run

**Comment by IoanaStanescu** [comment]
@evelynl94 Thanks, I've discovered later that it is added in that release. I will retry maybe it's something that I do wrong. 
@ yiranwang52 I am using makisu as a job in kubernetes, I give the following args to the makisu container:
`          args:
            - build
            - --push="<registry>"
            - --modifyfs=true
            - -t=makisu-test:0.0.1
            - --registry-config='{"<registry>":{".*":{"security":{"basic":{"username":"<username>","password":"<password>"}}}}}'
            - --redis-cache-addr=redis-makisu
            - /makisu-context`

**Pull request merged**
