### PR TITLE
Handle chown params of COPY and ADD

### LINKED ISSUE #185: Cannot change file permissions with `COPY`
Given:
```
$ tree
.
├── content
│   └── my.cfg
├── Dockerfile
└── storage

2 directories, 2 files
```
and
```
$ cat Dockerfile
FROM alpine
COPY --chown=0:0 . /srv
```
I'm trying to build an image on a regular host (not inside a container) as a regular (unprivileged) user without access to Docker daemon:
```
$ makisu build -t test01 --dest=out.tar --file=$(pwd)/Dockerfile --storage=$(pwd)/storage $(pwd)/content
{"level":"info","ts":1550690332.5627725,"msg":"Starting Makisu build (version=master-unreleased)"}
{"level":"info","ts":1550690332.583713,"msg":"Using build context: /tmp/tmp.92hhanBrdw/content"}
{"level":"info","ts":1550690332.5859363,"msg":"Using local file at /tmp/tmp.92hhanBrdw/storage/cache_key_value.json for cacheID storage"}
{"level":"info","ts":1550690332.586354,"msg":"No registry information provided, using cached layers"}
{"level":"error","ts":1550690332.5889933,"msg":"Failed to fetch intermediate layer with cache ID d77ace21: find layer d77ace21: layer not found in cache"}
{"level":"info","ts":1550690332.589024,"msg":"* Stage 1/1 : (alias=0,latestfetched=-1)"}
{"level":"error","ts":1550690332.594843,"msg":"failed to execute build plan: execute stage: build stage 0: fs not allowed to be modified"}
```
This actually doesn't change even if `makisu` is run as root inside a Docker container.

When adding `--modifyfs` it seems that `makisu` tries to delete all files under `/`:
```
$ makisu build -t test01 --dest=out.tar --file=$(pwd)/Dockerfile --modifyfs --storage=$(pwd)/storage $(pwd)/content
{"level":"info","ts":1550685258.3629878,"msg":"Starting Makisu build (version=master-unreleased)"}
{"level":"error","ts":1550685258.37333,"msg":"failed to remove file /.autorelabel: remove /.autorelabel: permission denied"}
...
```

As per conversations with @yiranwang52 [in Slack](https://uber-container-tools.slack.com/archives/CED2Y4UEM/p1550691073019300) it seems to be doable and it was suggested that it deserves an issue.

### PR DESCRIPTION
**Pull request by Rowern**
Should fix #185 
I might have forgotten a `chown` somewhere and the mem_fs solution is dirty so if you have any advice on this I would be happy to change this.

### CODE REVIEW

**Comment by Rowern** [comment]
Sorry, failed some git manipulation on my end...

**Comment by yiranwang52** [comment]
@edoakes do you remember why we didn't do this?

**Comment by yiranwang52** [comment]
I think with your current logic, if owner wasn't specified, all files will always be owned by the user running makisu (probably root), instead of preserving the previous ownership.

**Comment by edoakes** [comment]
I believe I implemented this at some point but it broke compatibility with the Docker build engine. Can you verify that this is the behavior exhibited by Docker before we merge it?

Also, there needs to be differentiation between the uid and gid not being set and being set to the root (0). Perhaps when they aren't set we can pass in a -1 and then handle that case separately?

**Comment by Rowern** [comment]
@edoakes From the doc: https://docs.docker.com/engine/reference/builder/#copy:
> All new files and directories are created with a UID and GID of 0, unless the optional --chown flag specifies a given username, groupname, or UID/GID combination to request specific ownership of the copied content.

But I'm going to do so testing with dockerfiles to see how it behaves.

**Comment by Rowern** [comment]
With this Dockerfile:

```Dockerfile
FROM node:10-alpine as builder

RUN env && mkdir /app && chown -R node:node /app

RUN mkdir /app2

COPY package.json /app2/

USER node

COPY --chown=node:node package.json /app/

COPY package.json /app2/package2.json

RUN ls -lah /app && ls -lah /app2
```

I get the output:
```
total 12
drwxr-xr-x    1 node     node        4.0K Apr 24 12:07 .
drwxr-xr-x    1 root     root        4.0K Apr 24 12:07 ..
-rw-r--r--    1 node     node         142 Apr 19 14:12 package.json
total 16
drwxr-xr-x    1 root     root        4.0K Apr 24 12:07 .
drwxr-xr-x    1 root     root        4.0K Apr 24 12:07 ..
-rw-r--r--    1 root     root         142 Apr 19 14:12 package.json
-rw-r--r--    1 root     root         142 Apr 19 14:12 package2.json
```

On makisu with this branch:
```
total 12
drwxr-xr-x    2 node     node        4.0K Apr 24 12:09 .
drwxr-xr-x    1 root     root        4.0K Apr 24 12:09 ..
-rw-r--r--    1 node     node         142 Apr 24 12:09 package.json
total 16
drwxr-xr-x    2 root     root        4.0K Apr 24 12:09 .
drwxr-xr-x    1 root     root        4.0K Apr 24 12:09 ..
-rw-r--r--    1 root     root         142 Apr 24 12:09 package.json
-rw-r--r--    1 root     root         142 Apr 24 12:09 package2.json
```

Is there a way to add this kind of test to the integration one ?

**Comment by edoakes** [comment]
Thanks for testing it - the dockerfile docs are sometimes underspecified from my experience.

Are the files that you're copying in owned by `root` on the host or by another user?

Yes, let's definitely add some testing for this. Definitely should have a unit test in the [CopyStep tests](https://github.com/uber/makisu/blob/master/lib/builder/step/copy_step_test.go) and an integration test would be great too. You can add a new test case by creating a new directory in the [testdata directory](https://github.com/uber/makisu/tree/master/testdata/build-context) (can model it after examples there) and then a new test function in the [python test file](https://github.com/uber/makisu/blob/master/test/python/test_build.py).

**Comment by Rowern** [comment]
@edoakes I'm running on MacOS so it might be a well suited env for this kind of tests but locally my files (used by my example Dockerfile) where not owned by `root` but by my local user.

I tried adding some unit tests but it might not be a good solution as changing ownership/group is not possible from a non root user and I didn't want to make this necessarry for unit tests to pass. I'm adding some integration tests now.

**Comment by yiranwang52** [comment]
can you rebase this on top of current master? that might help with the flaky test.

**Pull request merged**
