### PR TITLE
Fetching up-to-date CA certs from Debian ca-certificates

### PR DESCRIPTION
**Pull request by hatemosphere**
I don't really know if you guys would prefer this way of passing updated trusted CA certs since it's just another option to do it, without the need to update them manually.

Will try to submit another PR to fix issue #121 to support flow with self-hosted Docker registry running in private hosted zone (hopefully in a nearest future). Also it will be nice to remove hardcoded /makisu-internal/certs/cacerts.pem and use default CA flow from crypto/tls package instead, and then add custom CA bundles with command line arguments. What do you think about this?

### CODE REVIEW

**Comment by evelynl94** [comment]
> I don't really know if you guys would prefer this way of passing updated trusted CA certs since it's just another option to do it, without the need to update them manually.
> 
> Will try to submit another PR to fix issue #121 to support flow with self-hosted Docker registry running in private hosted zone (hopefully in a nearest future). Also it will be nice to remove hardcoded /makisu-internal/certs/cacerts.pem and use default CA flow from crypto/tls package instead, and then add custom CA bundles with command line arguments. What do you think about this?

Thanks for doing this! I think that is what we did in the past (we generated ca.pem from `ca-certificates`), but there was a particular reason why we changed it and I cannot recall now...Let me rethink about it a bit more.

**Comment by yiranwang52** [comment]
Looking at how DefaultCACertsPath is used and how TLSConfig is defined in the code, I think currently we assume the cert to be one files...@hatemosphere if you want to fix this, a slightly bigger change is needed.

**Comment by hatemosphere** [comment]
@yiranwang52 but my PR is not changing the cert file location - in the end it will be the same file

**Comment by hatemosphere** [comment]
@yiranwang52 oh wait, you mean that it won't work for a bare binary file, built from repo, not from Dockerfile? yeah, i guess the whole process of reading CA bundle needs to be changed

**Pull request closed without merging**
